#!/bin/bash

# Fail and exit immediately if any command doesn't succeed (e)
# or if any unbound variables lurk within (u)
set -eu

# Build the new image
docker build \
  --force-rm \
  --tag mirror-northflank-postgres-backups \
  --file Dockerfile \
  $@ ./

docker save --output mirror-northflank-postgres-backups_image.tar mirror-northflank-postgres-backups
