#!/bin/bash

docker run  \
  --env-file docker.env \
  --volume /home/robert/Documents/Docker/mirror-northflank-postgres-backups/data:/media/destination:rw \
  --rm \
  mirror-northflank-postgres-backups
